"""
report_generator.py — Generate a multi-page PDF summary report for ArthaSense.

Public API
----------
generate_pdf_report(df, stats, anomaly_summary, forecast_summary,
                    health_score, health_components,
                    recurring_df, ai_summary) -> bytes
    Returns the PDF as raw bytes ready for st.download_button.
"""

from __future__ import annotations

from io import BytesIO
from typing import Optional

import pandas as pd

# Colour constants (RGB tuples)
_BLUE      = (59,  130, 246)
_GREEN     = (16,  185, 129)
_RED       = (239, 68,  68)
_YELLOW    = (245, 158, 11)
_DARK      = (15,  23,  42)
_MID       = (71,  85,  105)
_LIGHT_BG  = (248, 250, 252)
_WHITE     = (255, 255, 255)
_BORDER    = (226, 232, 240)


def _format_inr(amount: float) -> str:
    """Format a number in Indian numbering system with Rs. prefix (PDF-safe)."""
    amount = abs(amount)
    if amount >= 1_00_00_000:
        return f"Rs.{amount / 1_00_00_000:.1f}Cr"
    if amount >= 1_00_000:
        return f"Rs.{amount / 1_00_000:.1f}L"
    if amount >= 1_000:
        return f"Rs.{amount:,.0f}"
    return f"Rs.{amount:.0f}"


def _safe(text: str, maxlen: int = 200) -> str:
    """Strip non-Latin-1 characters so fpdf2 built-in fonts don't crash."""
    out = []
    for ch in str(text)[:maxlen]:
        if ord(ch) < 256:
            out.append(ch)
        else:
            # Map common unicode punctuation to ASCII equivalents
            replacements = {
                "\u2014": "-", "\u2013": "-", "\u2019": "'", "\u2018": "'",
                "\u201c": '"', "\u201d": '"', "\u2026": "...", "\u2022": "*",
                "\u00b7": ".", "\u203a": ">", "\u2192": "->", "\u20b9": "Rs.",
                "\u00b7": ".", "\u00d7": "x",
            }
            out.append(replacements.get(ch, "?"))
    return "".join(out)


def generate_pdf_report(
    df: pd.DataFrame,
    stats: dict,
    anomaly_summary: dict,
    forecast_summary: pd.DataFrame,
    health_score: int,
    health_components: dict,
    recurring_df: pd.DataFrame,
    ai_summary: str = "",
) -> bytes:
    """
    Generate a 5-page ArthaSense summary PDF report.

    Page 1 : Key metrics + Health Score
    Page 2 : Category breakdown table
    Page 3 : Top 5 anomalies
    Page 4 : AI Advisor summary
    Page 5 : Recurring payments list

    Returns
    -------
    bytes — the complete PDF file content
    """
    try:
        from fpdf import FPDF, XPos, YPos
    except ImportError:
        raise ImportError(
            "fpdf2 is required for report generation. "
            "Run: pip install fpdf2"
        )

    class _PDF(FPDF):
        def header(self):
            self.set_fill_color(*_DARK)
            self.rect(0, 0, 210, 14, "F")
            self.set_font("Helvetica", "B", 9)
            self.set_text_color(*_WHITE)
            self.set_xy(10, 3)
            self.cell(0, 8, "ArthaSense - Finance Intelligence Report", align="L")
            self.set_xy(0, 3)
            self.cell(200, 8, f"Page {self.page_no()}", align="R")
            self.ln(4)

        def footer(self):
            self.set_y(-12)
            self.set_font("Helvetica", "", 7)
            self.set_text_color(*_MID)
            self.cell(0, 5, "Generated by ArthaSense  |  For personal use only", align="C")

        def section_title(self, title: str):
            self.set_fill_color(*_BLUE)
            self.set_text_color(*_WHITE)
            self.set_font("Helvetica", "B", 10)
            self.cell(0, 8, f"  {title}", fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            self.ln(3)

        def kpi_row(self, items: list[tuple[str, str]]):
            """Render a horizontal row of KPI boxes."""
            box_w = (190 - (len(items) - 1) * 4) / len(items)
            x0 = self.get_x()
            y0 = self.get_y()
            for label, value in items:
                self.set_xy(x0, y0)
                self.set_fill_color(*_LIGHT_BG)
                self.set_draw_color(*_BORDER)
                self.rect(x0, y0, box_w, 20, "FD")
                self.set_xy(x0 + 2, y0 + 2)
                self.set_font("Helvetica", "", 7)
                self.set_text_color(*_MID)
                self.cell(box_w - 4, 5, label, new_x=XPos.LEFT, new_y=YPos.NEXT)
                self.set_xy(x0 + 2, y0 + 8)
                self.set_font("Helvetica", "B", 11)
                self.set_text_color(*_DARK)
                self.cell(box_w - 4, 9, value)
                x0 += box_w + 4
            self.ln(24)

    pdf = _PDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_margins(10, 18, 10)

    # ── Determine date range string ───────────────────────────────────────
    dr = stats.get("date_range")
    dr_str = (
        f"{dr[0].strftime('%d %b %Y')} to {dr[1].strftime('%d %b %Y')}"
        if dr else "All time"
    )

    # ─────────────────────────────────────────────────────────────────────
    # PAGE 1 — Key Metrics + Health Score
    # ─────────────────────────────────────────────────────────────────────
    pdf.add_page()

    # Title block
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(*_DARK)
    pdf.ln(2)
    pdf.cell(0, 10, "Finance Intelligence Report", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*_MID)
    pdf.cell(0, 6, f"Period: {dr_str}   |   "
             f"{stats.get('transaction_count', 0):,} transactions",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    # KPI boxes (row 1)
    pdf.section_title("Key Metrics")
    total_debits  = stats.get("total_debits",  0)
    total_credits = stats.get("total_credits", 0)
    net_cashflow  = stats.get("net_cashflow",  0)
    avg_mo        = stats.get("avg_monthly_spend", 0)

    _net_sign = "+" if net_cashflow >= 0 else "-"
    pdf.kpi_row([
        ("Total Spend",   _format_inr(total_debits)),
        ("Total Income",  _format_inr(total_credits)),
        ("Net Cashflow",  _net_sign + _format_inr(abs(net_cashflow))),
        ("Avg/Month",     _format_inr(avg_mo)),
    ])

    # Health score breakdown
    pdf.section_title("Financial Health Score")
    pdf.set_font("Helvetica", "B", 28)
    if health_score >= 71:
        pdf.set_text_color(*_GREEN)
        band = "Healthy"
    elif health_score >= 41:
        pdf.set_text_color(*_YELLOW)
        band = "Moderate"
    else:
        pdf.set_text_color(*_RED)
        band = "At Risk"
    pdf.cell(30, 14, str(health_score))
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 14, f"/ 100  -  {band}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)

    # Component bars
    _comp_rows = [
        ("Savings Rate",      health_components.get("savings_pts",  0), 25),
        ("Expense Diversity", health_components.get("diversity_pts", 0), 25),
        ("Anomaly Rate",      health_components.get("anomaly_pts",   0), 25),
        ("Forecast Trend",    health_components.get("trend_pts",     0), 25),
    ]
    for lbl, pts, maxp in _comp_rows:
        pct = pts / maxp
        bar_color = _GREEN if pct >= 0.70 else (_YELLOW if pct >= 0.40 else _RED)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*_MID)
        pdf.cell(55, 6, lbl)
        # bar
        pdf.set_fill_color(*_BORDER)
        pdf.rect(pdf.get_x(), pdf.get_y() + 1, 80, 4, "F")
        pdf.set_fill_color(*bar_color)
        pdf.rect(pdf.get_x(), pdf.get_y() + 1, 80 * pct, 4, "F")
        pdf.set_x(pdf.get_x() + 84)
        pdf.set_text_color(*_DARK)
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(20, 6, f"{pts} / {maxp}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # Tips
    tips = health_components.get("tips", [])
    if tips:
        pdf.ln(3)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*_BLUE)
        pdf.cell(0, 6, "Improvement Tips", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*_MID)
        for tip in tips:
            pdf.cell(5, 5, ">")
            pdf.cell(0, 5, _safe(tip, 100), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # ─────────────────────────────────────────────────────────────────────
    # PAGE 2 — Category Breakdown
    # ─────────────────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("Category Breakdown")

    if "category" in df.columns:
        cat_df = (
            df[df["transaction_type"] == "debit"]
            .groupby("category")["debit"].sum()
            .sort_values(ascending=False)
            .reset_index()
        )
        cat_df.columns = ["Category", "Total Spent"]
        total_s = cat_df["Total Spent"].sum()

        # Table header
        col_w = [80, 35, 30, 35]
        headers = ["Category", "Total Spent", "% of Total", "Transactions"]
        pdf.set_fill_color(*_DARK)
        pdf.set_text_color(*_WHITE)
        pdf.set_font("Helvetica", "B", 8)
        for i, h in enumerate(headers):
            pdf.cell(col_w[i], 7, h, fill=True, border=1)
        pdf.ln()

        txn_counts = (
            df[df["transaction_type"] == "debit"]
            .groupby("category").size()
        )

        # Table rows
        pdf.set_font("Helvetica", "", 8)
        for i, (_, row_data) in enumerate(cat_df.iterrows()):
            cat   = str(row_data["Category"])
            spent = float(row_data["Total Spent"])
            pct   = spent / total_s * 100 if total_s > 0 else 0
            txns  = int(txn_counts.get(cat, 0))
            fill_bg = _LIGHT_BG if i % 2 == 0 else _WHITE
            pdf.set_fill_color(*fill_bg)
            pdf.set_text_color(*_DARK)
            pdf.cell(col_w[0], 6, cat[:38], fill=True, border=1)
            pdf.cell(col_w[1], 6, _format_inr(spent), fill=True, border=1, align="R")
            pdf.cell(col_w[2], 6, f"{pct:.1f}%", fill=True, border=1, align="R")
            pdf.cell(col_w[3], 6, str(txns), fill=True, border=1, align="R")
            pdf.ln()
    else:
        pdf.set_text_color(*_MID)
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(0, 8, "No category data available.")

    # ─────────────────────────────────────────────────────────────────────
    # PAGE 3 — Top 5 Anomalies
    # ─────────────────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("Top 5 Anomalous Transactions")

    n_anom = anomaly_summary.get("total_anomalies", 0)
    total_flagged = anomaly_summary.get("total_flagged_amount", 0)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*_MID)
    pdf.cell(0, 6,
             f"{n_anom} anomal{'y' if n_anom == 1 else 'ies'} detected  |  "
             f"{_format_inr(total_flagged)} flagged",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)

    if "is_anomaly" in df.columns:
        anom_df = (
            df[df["is_anomaly"] == True]
            .sort_values("anomaly_score", ascending=False)
            .head(5)
        )
        for i, (_, row_data) in enumerate(anom_df.iterrows()):
            score = float(row_data.get("anomaly_score", 0))
            if score >= 0.80:
                sev, sev_color = "CRITICAL", _RED
            elif score >= 0.72:
                sev, sev_color = "HIGH", _YELLOW
            else:
                sev, sev_color = "MEDIUM", _MID

            date_str = (row_data["date"].strftime("%d %b %Y")
                        if pd.notna(row_data.get("date")) else "-")
            desc    = str(row_data.get("description", ""))[:50]
            amount  = _format_inr(float(row_data.get("debit", 0)))
            reason  = str(row_data.get("anomaly_reason", ""))[:80]
            cat     = str(row_data.get("category", ""))

            pdf.set_fill_color(*_LIGHT_BG)
            pdf.set_draw_color(*_BORDER)
            pdf.rect(10, pdf.get_y(), 190, 22, "FD")
            pdf.set_xy(12, pdf.get_y() + 2)

            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(*sev_color)
            pdf.cell(22, 5, sev)
            pdf.set_text_color(*_MID)
            pdf.set_font("Helvetica", "", 8)
            pdf.cell(0, 5, f"{date_str}   |   Score {score:.3f}",
                     new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.set_x(12)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*_DARK)
            pdf.cell(120, 5, desc)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*_RED)
            pdf.cell(0, 5, amount, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.set_x(12)
            pdf.set_font("Helvetica", "", 7)
            pdf.set_text_color(*_MID)
            pdf.cell(0, 5, _safe(f"{cat}   |   {reason}", 100), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.ln(3)
    else:
        pdf.set_text_color(*_MID)
        pdf.cell(0, 8, "No anomaly data available.")

    # ─────────────────────────────────────────────────────────────────────
    # PAGE 4 — AI Advisor Summary
    # ─────────────────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("AI Advisor Summary")

    if ai_summary:
        text = ai_summary[:2000]          # cap for PDF layout
    else:
        cr = stats.get("total_credits", 0)
        db = stats.get("total_debits",  0)
        sr = (cr - db) / cr * 100 if cr > 0 else 0
        text = (
            f"Statement period: {dr_str}\n\n"
            f"Total spend: {_format_inr(db)}  |  Total income: {_format_inr(cr)}  |  "
            f"Net cashflow: {_format_inr(cr - db)}\n\n"
            f"Savings rate: {sr:.1f}%\n\n"
            f"Financial health score: {health_score}/100 ({band})\n\n"
            f"Anomalies detected: {n_anom}\n\n"
            f"Review the Categories and Anomalies tabs in ArthaSense for detailed insights."
        )

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*_DARK)
    pdf.multi_cell(0, 5.5, _safe(text, 2000))

    # ─────────────────────────────────────────────────────────────────────
    # PAGE 5 — Recurring Payments
    # ─────────────────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("Recurring Payments")

    if not recurring_df.empty:
        total_monthly_r = recurring_df[recurring_df["likely_subscription"]]["avg_amount"].sum()
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*_MID)
        pdf.cell(0, 6,
                 f"{len(recurring_df)} recurring merchants detected  |  "
                 f"Est. monthly cost: {_format_inr(total_monthly_r)}",
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(2)

        col_w2 = [70, 28, 28, 30, 20]
        headers2 = ["Merchant", "Occurrences", "Avg Amount", "Total Spent", "Sub?"]
        pdf.set_fill_color(*_DARK)
        pdf.set_text_color(*_WHITE)
        pdf.set_font("Helvetica", "B", 8)
        for i, h in enumerate(headers2):
            pdf.cell(col_w2[i], 7, h, fill=True, border=1)
        pdf.ln()

        pdf.set_font("Helvetica", "", 8)
        for idx, (_, row_data) in enumerate(recurring_df.iterrows()):
            fill_bg = _LIGHT_BG if idx % 2 == 0 else _WHITE
            pdf.set_fill_color(*fill_bg)
            pdf.set_text_color(*_DARK)
            pdf.cell(col_w2[0], 6, str(row_data["merchant"])[:35], fill=True, border=1)
            pdf.cell(col_w2[1], 6, str(int(row_data["frequency"])), fill=True, border=1, align="R")
            pdf.cell(col_w2[2], 6, _format_inr(float(row_data["avg_amount"])), fill=True, border=1, align="R")
            pdf.cell(col_w2[3], 6, _format_inr(float(row_data["total_spent"])), fill=True, border=1, align="R")
            is_sub = row_data.get("likely_subscription", False)
            pdf.set_text_color(*_GREEN if is_sub else _MID)
            pdf.cell(col_w2[4], 6, "Yes" if is_sub else "No", fill=True, border=1, align="C")
            pdf.ln()
            pdf.set_text_color(*_DARK)
    else:
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*_MID)
        pdf.cell(0, 8, "No recurring payment patterns detected.")

    # ── Output ────────────────────────────────────────────────────────────
    buf = BytesIO()
    pdf.output(buf)
    return buf.getvalue()
